version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: chat-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: chatdb
      MYSQL_USER: chatuser
      MYSQL_PASSWORD: chatpass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-prootpassword"]
      interval: 5s
      retries: 10
      start_period: 10s
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: chat-backend
    restart: on-failure
    env_file:
      - ./backend/.env
    ports:
      - "4000:4000"
    depends_on:
      mysql:
        condition: service_healthy
    command: npm run dev
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: chat-frontend
    restart: on-failure
    environment:
      - API_INTERNAL=http://chat-backend:4000/api
      - NEXT_PUBLIC_API_BASE=http://localhost:4000/api
      - NEXT_PUBLIC_SOCKET_URL=http://localhost:4000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    command: npm run dev
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
