const express = require('express');
const cors = require('cors');
const path = require('path');
const cookieParser = require('cookie-parser');
const authRoutes = require('./routes/auth');
const convRoutes = require('./routes/conversations');
const msgRoutes = require('./routes/messages');
const userRoutes = require('./routes/users');
const app = express();
// allow browser at localhost:3000 and internal SSR
app.use(cors({ origin: ['http://localhost:3000','http://127.0.0.1:3000'], credentials: true }));
app.use(express.json());
app.use(cookieParser());
app.use('/uploads', express.static(path.join(__dirname, 'uploads')));
app.get('/api/health', (req,res)=> res.json({ status: 'ok' }));
app.use('/api/auth', authRoutes);
app.use('/api/conversations', convRoutes);
app.use('/api/messages', msgRoutes);
app.use('/api/users', userRoutes);
module.exports = app;
